### ISSUE TITLE
Update macos-release + win-release deps

### ISSUE THREAD

**Issue by rskvazh** [sindresorhus/os-name#6] opened 2018-11-12 10:01 UTC
Hi.
There is dependencies on old versions of macos-release + win-release

**Comment by sindresorhus** [comment] 2018-11-12 10:20
Duplicate of #5

**Closed by sindresorhus** 2018-11-12 10:20 UTC

**Comment by jssuttles** [comment] 2020-08-04 17:27
https://github.com/sindresorhus/os-name/blob/master/package.json depends on an older version of windows-release which does not contain Windows Server 2019. I can make a new issue if needed.
